spring:
  application:
    name: feedback-service   # unique per service
  datasource:
    url: jdbc:postgresql://localhost:5434/feedback_db
    username: feedback_user
    password: feedback_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0

rabbitmq:
  exchange:
    feedback: feedback.exchange
  routing-key:
    feedback-submitted: feedback.submitted

logging:
  level:
    org.hibernate.SQL: DEBUG
    no.kristiania.echocare: DEBUG

server:
  port: 8083

jwt:
  secret: WOwTER+0vZAxLEr3LtLzJY1Y77gWWnnuQeUrvvTA9ZKvH47wGBwv1kJ+ghqrn7basSlRTQjjXNsaMJdZNbQRIw==