spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://localhost:5435/profile_db
    username: profile_user
    password: profile_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Change to 'update' for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081

# JWT Configuration (if using Spring Security)
jwt:
  secret: WOwTER+0vZAxLEr3LtLzJY1Y77gWWnnuQeUrvvTA9ZKvH47wGBwv1kJ+ghqrn7basSlRTQjjXNsaMJdZNbQRIw==
