spring:
  application:
    name: playlist-service

  datasource:
    url: jdbc:postgresql://localhost:5433/playlist_db
    username: playlist_user
    password: playlist_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /playlist

jwt:
  secret: WOwTER+0vZAxLEr3LtLzJY1Y77gWWnnuQeUrvvTA9ZKvH47wGBwv1kJ+ghqrn7basSlRTQjjXNsaMJdZNbQRIw==