###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123",
    "email": "admin@adsmin.com"
}

###

GET http://localhost:8080/api/caregivers
